"""Inicial

Revision ID: 6e5bcd64ee01
Revises: 
Create Date: 2022-01-04 13:41:41.679563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5bcd64ee01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_cnpj'), 'company', ['cnpj'], unique=False)
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=False)
    op.create_index(op.f('ix_company_endereco'), 'company', ['endereco'], unique=False)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_nome'), 'company', ['nome'], unique=False)
    op.create_index(op.f('ix_company_razao_social'), 'company', ['razao_social'], unique=False)
    op.create_index(op.f('ix_company_telefone'), 'company', ['telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_telefone'), table_name='company')
    op.drop_index(op.f('ix_company_razao_social'), table_name='company')
    op.drop_index(op.f('ix_company_nome'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_endereco'), table_name='company')
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_index(op.f('ix_company_cnpj'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
